### ISSUE TITLE
Managing low batteries with dashboards, notifications and automations 🔋

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#60]
# Objective
Receive a notification when batteries are getting critical ```< 10%``` or low ```10%-20%``` or those that are unavailable. 

# Features
* [x] Lovelace panel to track battery levels.
* [x] Entity filter card to provide a focused view of low and critical batteries.
* [x] Daily automation to provide notification of low batteries (persistent but not annoyingly so).
* [x] Automated pro-active maintenance process (DevOps) to create GitHub issue when device has a low battery. #103 
* [x] TTS announcements.
* [x] Grafana dashboards to provide useful insights into battery data.  

Related to #51, #103

**Comment by jcallaghan** [comment]
## Lovelace 
Firstly before I kick any automation I decided to do create the Lovelace panel to give me a view of things. Want this has shown me is I had a sh*t load of batteries yet I've never really had a problem with this.

![image](https://user-images.githubusercontent.com/7449908/81913952-90967a00-95c8-11ea-8595-6e3608215c4c.png)

## Low and Critical Batteries
After getting all the devices into cards I decided to add to filter cards to show me devices with low batteries (<20%) and those with critical batteries (unavailable or less than 20%).

![image](https://user-images.githubusercontent.com/7449908/81914538-57aad500-95c9-11ea-8450-97c394ca402e.png)

### Critical battery filter card
The critical battery filter card uses two filters and looks like this:

```yaml
card:
  show_header_toggle: false
  title: Critical Batteries
entities:
  - entity: sensor.battery
state_filter:
  - operator: <
    value: 10
  - operator: ==
    value: unavailable
type: entity-filter
```

### Low battery filter card
The low battery filter card looks like this:

```
card:
  show_header_toggle: false
  title: Critical Batteries
entities:
  - entity: sensor.battery
state_filter:
  - operator: <
    value: 20
type: entity-filter
```

**Comment by jcallaghan** [comment]
# Grafana 
I was interested to see how long it was between batteries cycles so I've created a dashboard to report on battery levels. This example is of the devices in my back garden but I'm curious if I should do this on a room-by-room basis or by a thing-type basis such as Ring, Aqara, Hue etc.

![image](https://user-images.githubusercontent.com/7449908/83364175-2dae2c80-a397-11ea-9aad-0557f66e237e.png)

**Comment by jcallaghan** [comment]
# Automation
Leverage examples such as:
* https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/packages/battery_levels.yaml
* https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/packages/battery_levels.yaml?rgh-link-date=2017-11-23T16%3A30%3A11Z
* https://community.home-assistant.io/t/howto-create-battery-alert-without-creating-a-template-for-every-device/30576/34
* https://community.home-assistant.io/t/how-do-i-trigger-based-on-a-substring-of-a-bunch-of-sensors/3164/17?u=tscibilia

**Comment by jcallaghan** [comment]
# Observations

Few observations I have made during this exercise.
* [ ] Hue outdoor sensors can't be reporting correctly as they have shown 100% since the start of the dataset.
* [ ] I can't seem to the data back for the battery level of my Ring Alarm entities where this is help as an attribute alongside the main binary_sensor entity.

![image](https://user-images.githubusercontent.com/7449908/83437178-322a2200-a437-11ea-9b9b-c7921269e094.png)

**Comment by jcallaghan** [comment]
[Shared on Twitter](https://twitter.com/jamescallaghan/status/1267561256350818304).

**Comment by jcallaghan** [comment]
# Battery level gauges

[Rui Espinho](https://twitter.com/ruiespinho/status/1267583038889889794) asked on Twitter how I made the batter level gauges. These are made by leveraging the bar gauge visualisation in a Grafana dashboard along with some thresholds to align to my low (20%) and critical levels (10%).

![image](https://user-images.githubusercontent.com/7449908/83462294-be057380-a462-11ea-9cae-f511726519fc.png)

**Comment by jcallaghan** [comment]
# How to: Grafana queries
[Matthias Matousek (@m_matou) asked on Twitter](https://twitter.com/m_matou/status/1267755186556190720) how I achieve the queries for batteries.

Depending on how the battery data is reported you may need to try different queries.

## State method



## Attribute method

**Comment by jcallaghan** [comment]
# Todo
* Automation/package https://raw.githubusercontent.com/notoriousbdg/Home-AssistantConfig/master/packages/battery_alert.yaml
* Attribute-based battery level - Ring alarm sensors
* Monitor 100% batteries - if they're not moving something might be wrong with the reporting
* Does Tado publish battery via API? 
* Home Assistant notification
* Morning TTS routine
* Dynamic filter card to avoid having to keep my Lovelace panel and cards up-to-date

**Comment by jcallaghan** [comment]
# History
```
history:
  exclude:
    entities:
      - automation.battery_persistent_notification
      - automation.battery_persistent_notification_clear
      - automation.battery_notification_default
      - automation.battery_notification_slack
      - automation.battery_sensor_from_attributes
      - automation.update_battery_status_group_members
      - automation.update_battery_low_group_members
      - automation.remove_battery_low_group
      - automation.delete_battery_sensor
```

**Comment by jcallaghan** [comment]
# GitHub API

## Testing

So it was always going to end up here in my view. Automated maintenance tasks. It was more deciding to use issues in this repo or creating a task in Microsoft Todo. I may still do this for testing and fun anyway. 

Leveraging [Postman](https://www.postman.com/) to test the GitHub API I was able to create a new issue. Postman is great for testing APIs! You can also use parameters in the URL to fill prepare an issue: ```https://github.com/jcallaghan/home-assistant-config/issues/newtitle=test&body=test&labels=battery,task:%20maintenance```.

![image](https://user-images.githubusercontent.com/7449908/84328570-34e4ef80-ab7a-11ea-86b8-6b9a3ec92c2e.png)

1. Generate new personal access token (with full repo access) ```https://github.com/settings/tokens```
1. API POST endpoint ```https://api.github.com/repos/jcallaghan/home-assistant-config/issues```
1. Set authentication method to Oauth using the access token generated above
1. Body
```JSON
{
  "title": "Test",
  "body": "Test",
  "labels": [
    "battery",
    "task: maintenance"
  ]
}
```
## Rest command
Using the rest_command integrated I created the following service.
```
rest_command:
  new_github_issue_replace_battery:
    url: https://api.github.com/repos/jcallaghan/home-assistant-config/issues
    method: POST
    headers:
      Authorization: !secret github_token
    payload: '{"title":"{{ title }}","body":"{{ message }}","labels":["battery","task: maintenance"]}'
```

### secrets.yaml
Don't forget to add ```Bearer ``` in front of your access token in your secrets file.
```
github_token: "Bearer 000000000000000"
```

## Automation/service

Service name:
```rest_command.new_github_issue_replace_battery```
Service data: 
```
{ 
  "title": "Service test",
  "message": "Create via service call in Home Assistant"
}
```
![image](https://user-images.githubusercontent.com/7449908/84329850-bbe79700-ab7d-11ea-98ee-f7ac1099741d.png)

## Reference
* https://developer.github.com/v3/issues/#create-an-issue
* https://developer.github.com/v3/auth/#via-oauth-and-personal-access-tokens
* https://www.postman.com/
* https://developer.github.com/v3/
* https://www.home-assistant.io/integrations/rest_command/

**Comment by jcallaghan** [comment]
# Filter error
I just noticed my low battery ```entity-filter``` card was not working as expected. Turns out I wasn't able to perform an AND filter so switched to using a regex pattern.

Using a great regex tool (https://regexr.com/)[https://regexr.com/] I was able to test an expression that would return numbers in the 11-20 range.

![image](https://user-images.githubusercontent.com/7449908/84592573-989f3f00-ae3e-11ea-9f96-26a75876d5b5.png)

```
state_filter:
  - operator: regex
    value: \b(1[1-9]|2[0])\b'
```

**Comment by jcallaghan** [comment]
# The big battery loop
I understand why folks use the big loop to check battery status dynamically as adding each battery-related entity and maintaining them manually is a real pain. But while creating a solution to notify me when I have a low battery today I came across a few things which have led me to create a hybrid approach building on [@Carlos's work CCOSTAN/Home-AssistantConfig#269](https://github.com/CCOSTAN/Home-AssistantConfig/issues/269).

## Template sensors
Carlos leverages an approach using a template sensor with a domain-based for loop where the word battery is either found in the entity name or a battery_level attribute is defined. The sensor value consists of the entity name and battery level which Carlos goes on to use with his TTS engine. 

While experimenting with the template I found I had various text-based values being returned which I excluded and at the time due to the number of sensors being returned by the template I hit the sensor text limit causing an value of ```unknown``` to be thrown. This was when I decided to split out the sensor into three, critical batteries (0-10%), low batteries (10-20%), and those that are unavailable. To achieve this I added two variables to define a threshold range.

Once I created the sensor and move from the template developer tool I noticed that the sensor wasn't updating. This is because the sensor wasn't associated to [any entities](https://www.home-assistant.io/integrations/binary_sensor.template/#entity-ids). To update the sensor you need to call the ```service_ homeassistant.update_entity``` service. Another alternative is binding it to sensor.date, sensor.hour or sensor.minute which will update the sensor daily, hourly, or every minute.

## Binary sensor
To make things a little nicer on the UI side I created a binary sensor for each template sensor. The state of the binary sensor is true when a battery falls within the applicable range. I still need to settle on the right [device_class](https://www.home-assistant.io/integrations/binary_sensor/#device-class). I'm also tempted to use a [template icon](https://www.home-assistant.io/integrations/binary_sensor.template/#change-the-icon-when-state-changes) to make it more obvious when the sensor is on or not.

![image](https://user-images.githubusercontent.com/7449908/84956396-05416480-b0f1-11ea-8710-77441980d78d.png)

## Extensibility 
I really like the extensibility of an approach shared in the [community forum](https://community.home-assistant.io/t/howto-create-battery-alert-without-creating-a-template-for-every-device/30576/701) that leverages MQTT to maintain configuration. I don't plan to use this for batteries but I do like the concept for some other ideas I have. 

## Further considerations
Right now I have automations for all three of my ranges (critical, low, and unavailable) which send a notification through to my phone. This is great but I'd still like to build some automated DevOps into this although with this automations that won't be possible as these are generic i.e. any battery is with one of these ranges. If I create an additional automation that triggers when a single entity falls into my low range I should be able to create a GitHub issue for me to replace the sensor battery. I'll work on this tomorrow and commit the code to share with you all.

**Comment by jcallaghan** [comment]
# GitHub issues for low batteries
Well with the additional automation I'm able to create a GitHub issue when a device has a low battery which is pretty cool. I might replicate this for sensors that have become unavailable for an extended time too.

![image](https://user-images.githubusercontent.com/7449908/85076930-105fc780-b1b9-11ea-86ff-40a7af514f68.png)

**Comment by jcallaghan** [comment]
# Closing out.
It has taken a few weeks but I've achieved everything I wanted to and some (for now at least). 
This single issue and idea has leveraged stuff I already knew about and a ton of new stuff I've learned about but most of all it was fun and has allowed me to build on the work and ideas of others and share something back with a little edge to it.

* It led me to consider some other ideas such as a notification engine #83 and issues to manage upgrades #105.
* It's allowed me to explore the GitHub rest APIs alongside Home Assistants rest and rest_command integrations #103.
* It provided me with a ton of data to present in Grafana dashboards.
* And those Grafana dashboards have already proven useful, where some of my Zigbee sensors dropped of the network. At first, I thought it was batteries but I was able to see when I last changed them and confirm they weren't low but instead had lost connectivity.
* And for now at least, I have a job for life to maintain all the entities in the Lovelace panels, Grafana dashboards while also keeping my selective list of entities that trigger an immediate notification up-to-date.

**Comment by jcallaghan** [comment]
# Throttling required
Seems overnight a device (Hue remote) rushed my new automation. I disabled the automation as soon as I realised it was triggering over and over. On closer inspection, the battery level fluctuates enormously so I'll need to get my thinking cap on and work our how I deal with this as a simple ```numeric_state``` trigger with ```below: 20``` and  ```for: 00:01:00``` isn't going to cut it.

![image](https://user-images.githubusercontent.com/7449908/85116382-226f5380-b215-11ea-813a-e3ac48a277b9.png)

**Comment by jcallaghan** [comment]
# Throttling required
Seems overnight a device (Hue remote) rushed my new automation. I disabled the automation as soon as I realised it was triggering over and over. On closer inspection, the battery level fluctuates enormously so I'll need to get my thinking cap on and work our how I deal with this as a simple ```numeric_state``` trigger with ```below: 20``` and  ```for: 00:01:00``` isn't going to cut it.

![image](https://user-images.githubusercontent.com/7449908/85116382-226f5380-b215-11ea-813a-e3ac48a277b9.png)

**Comment by jcallaghan** [comment]
Further ideas > https://github.com/notoriousbdg/Home-AssistantConfig/blob/master/packages/battery_alert.yaml

Also factor in monitored and unmonitored devices.

**Comment by jcallaghan** [comment]
## Template to help find sensors with a battery

```yaml
{% set domains = ['light', 'switch', 'sensor', 'lock', 'binary_sensor'] %}
{%- for domain in domains -%}
{%- for item in states[domain] if (item.attributes.battery_level is defined) or ("battery" in item.name | lower) -%}
  - entity_id: {{ item.entity_id }}
{% endfor %}
{%- endfor -%}
```
